### ISSUE TITLE
Improve basic formatting, naming and code patterns

### ISSUE THREAD

**Issue by vermorel** [Lokad/BitcoinNet#17]
In modern C#, trivial properties like:

```
public Script ScriptPubKey
{
	get
	{
		return GetAddress().ScriptPubKey;
	}
}
```

are expected to rewritten as

```
public Script ScriptPubKey => GetAddress().ScriptPubKey;
```

The codebase is showing its age, and should be modernized with the niceties of the latest C# version.

**Comment by osman-turan** [comment]
I think, some other code modernizations should be covered with this issue such as including but not limited:

- Removing unused namespaces
- Fixing inconsistent naming convention
- Implementing inline out variables
- Replacing explicitly typed local variables with implicitly typed local variables (i.e. `var` keyword)
- Sorting namespaces, nested-classes and class members
- Adding explicit access modifiers where implicitly defined (e.g. `private`)
- Use of `nameof` where applicable (such as exceptions)
- Fixing code indentation

What do you think?

**Comment by vermorel** [comment]
Can't agree more!
