### ISSUE TITLE
Remove BouncyCastle.Math dependency from ScriptReader.cs

### ISSUE THREAD

**Issue by vermorel** [Lokad/BitcoinNet#21]
We have an accidental dependency in `ScriptReader.cs` to `BitcoinNet.BouncyCastle.Math` which should be removed. There is only a single call to convert a `long` in `byte`. I believe there are ways to do without an external dependency. Less-than-ideal-but-better-still would be to use BCL [BigInteger](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger).

**Comment by osman-turan** [comment]
Implemented without use of `BigInteger` at all in #39.
