### ISSUE TITLE
Remove all wallet-features of RPC

### ISSUE THREAD

**Issue by vermorel** [Lokad/BitcoinNet#22]
In `RPCClient.cs`, we get an overview of the supported RPC features. All the _wallet_ features should be removed from BitcoinNet. Nowadays wallets are operated separately as they have rather specific security concerns.

**Comment by osman-turan** [comment]
By the way, according to Bitcoin Core node source, `fundrawtransaction` is implemented in `rpcwallet.cpp`. But, it's category is listed as `rawtransactions`, not `wallet`. There is a related method in BitcoinNet. Should I remove it as well?

https://github.com/bitcoin/bitcoin/blob/e74649e95122c9c61aadf607461cf701c3953f88/src/wallet/rpcwallet.cpp#L4118-L4124

**Comment by vermorel** [comment]
Yes, indeed, please remove it as well.
