### ISSUE TITLE
Isolate RPC as BitcoinNet.JsonRPC

### ISSUE THREAD

**Issue by vermorel** [Lokad/BitcoinNet#23]
The JSON-RPC logic should be isolated into a separate project `BitcoinNet.JsonRPC`. The `ReadMe.md` should indicate that the corresponding documentation of the protocol is to be found at https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/JSON-RPC.md

**Comment by osman-turan** [comment]
According Microsoft C# naming convention, shouldn't the project name and namespace be `BitcoinNet.JsonRpc`?

**Comment by vermorel** [comment]
Agreed :-)
