### ISSUE TITLE
Remove TraceSource.cs

### ISSUE THREAD

**Issue by vermorel** [Lokad/BitcoinNet#7]
BitcoinNet only intends to support .NET Core 2.1 and later. `TraceSource.cs` is a work-around that seems to be dedicated to some other flavor of .NET; I suggest to remove this class as it is now merely a trivial wrapper.

**Comment by osman-turan** [comment]
Is there anything left related to this issue? I believe, it's fixed in #29

**Comment by vermorel** [comment]
Indeed!
